apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trdgame-db-pv-claim
  namespace: trdgame
  labels:
    app: trdgame
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
